---
deployment:
  tasks:
    - echo "starting deployment"
    - export DJANGO_VENV_PATH=$HOME/virtualenv/django_api/3.12/bin/activate
    - export NODE_VENV_PATH=$HOME/nodevenv/react_app/22/bin/activate
    - export DJANGO_PATH=$HOME/django_api
    - export REACT_PATH=$HOME/react_app
    - export REP_DJANGO_PATH=$HOME/repositories/boattrade/boattrade-api
    - export REP_REACT_PATH=$HOME/repositories/boattrade/boattrade-frontend

    # copy from the repository to the deployment folder
    - rsync -av $REP_DJANGO_PATH/ $DJANGO_PATH
    - rsync -av $REP_REACT_PATH/ $REACT_PATH

    # setup python environment
    - source $DJANGO_VENV_PATH
    - pip install -r $DJANGO_PATH/requirements.txt
    - python3 $DJANGO_PATH/manage.py migrate
    - python3 $DJANGO_PATH/manage.py collectstatic --noinput

    # setup react environment
    - source $NODE_VENV_PATH
    - cd $REACT_PATH
    - npm install
    - npx vite build --mode production
    # move the build folder to the public folder
    - rsync -av --delete $REACT_PATH/build/ $DJANGO_PATH/public/


    
