deployment:
  tasks:
    - export DJANGO_DIR=$HOME/boattrade_api
    - export REACT_DIR=$HOME/boattrade_frontend
    - export VENV_DIR=$HOME/boattrade_api/.venv

    # Backend Setup
    - echo "Activating virtual environment"
    - if [ ! -d "$VENV_DIR" ]; then python3 -m pip install --user virtualenv; python3 -m virtualenv $VENV_DIR; fi
    - source $VENV_DIR/bin/activate
    - pip install --upgrade pip
    - pip install -r $DJANGO_DIR/requirements.txt
    - python3 $DJANGO_DIR/manage.py migrate
    - python3 $DJANGO_DIR/manage.py collectstatic --noinput
    - python3 $DJANGO_DIR/manage.py createsuperuser --noinput || true

    # Frontend Setup
    - echo "Building React app"
    - cd $REACT_DIR
    - npm install
    - npm run build
    - mkdir -p $DJANGO_DIR/static/
    - rsync -a $REACT_DIR/build/ $DJANGO_DIR/static/

    # Restart server
    - echo "Restarting application"
    - mkdir -p $DJANGO_DIR/tmp
    - touch $DJANGO_DIR/tmp/restart.txt
