deployment:
  tasks:
    - export DJANGO_DIR=$HOME/boattrade-api
    - export REACT_DIR=$HOME/boattrade-frontend
    - export VENV_DIR=$HOME/boattrade-api/.venv

    # Backend Setup
    - echo "Activating virtual environment"
    - python3 -m venv $VENV_DIR
    - source $VENV_DIR/bin/activate
    - pip install --upgrade pip
    - pip install -r $DJANGO_DIR/requirements.txt
    - python $DJANGO_DIR/manage.py migrate
    - python $DJANGO_DIR/manage.py collectstatic --noinput
    - python $DJANGO_DIR/manage.py createsuperuser --noinput || true

    # Frontend Setup
    - echo "Building React app"
    - cd $REACT_DIR
    - npm install
    - npm run build
    - rsync -a $REACT_DIR/build/ $DJANGO_DIR/static/

    # Restart server
    - echo "Restarting application"
    - touch $DJANGO_DIR/tmp/restart.txt
