# Generated by Django 5.1.7 on 2025-03-18 23:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sellrequest",
            options={
                "verbose_name": "Demande de mise en vente",
                "verbose_name_plural": "Demandes de mise en vente",
            },
        ),
        migrations.AlterField(
            model_name="boat",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Date de création de l'annonce",
            ),
        ),
        migrations.AlterField(
            model_name="boat",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Longueur (m)",
            ),
        ),
        migrations.AlterField(
            model_name="boat",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de mise à jour de l'annonce"
            ),
        ),
        migrations.AlterField(
            model_name="boat",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Largeur (m)",
            ),
        ),
    ]
