# Generated by Django 5.1.7 on 2025-03-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0002_alter_sellrequest_options_alter_boat_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boat",
            name="amenities",
            field=models.JSONField(
                blank=True,
                help_text="JSON format with exterior and interior lists",
                null=True,
                verbose_name="Équipements",
            ),
        ),
        migrations.AddField(
            model_name="boat",
            name="location",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Localisation"
            ),
        ),
        migrations.AddField(
            model_name="boat",
            name="technical_details",
            field=models.JSONField(
                blank=True,
                help_text="JSON format with equipment categories and details",
                null=True,
                verbose_name="Détails techniques",
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone"),
        ),
    ]
