# Generated by Django 5.1.7 on 2025-03-19 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_app",
            "0003_boat_amenities_boat_location_boat_technical_details_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boat",
            name="amenities",
        ),
        migrations.RemoveField(
            model_name="boat",
            name="technical_details",
        ),
        migrations.CreateModel(
            name="AmenityItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("interior", "Intérieur"), ("exterior", "Extérieur")],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Équipement")),
                (
                    "boat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenity_items",
                        to="api_app.boat",
                        verbose_name="Bateau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Équipement",
                "verbose_name_plural": "Équipements",
            },
        ),
        migrations.CreateModel(
            name="TechnicalDetailItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electricity_equipment", "Électricité / Annexe"),
                            ("rigging_sails", "Accastillage / Voiles"),
                            ("electronics", "Électronique"),
                        ],
                        max_length=50,
                        verbose_name="Catégorie",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("value", models.CharField(max_length=200, verbose_name="Valeur")),
                (
                    "boat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_detail_items",
                        to="api_app.boat",
                        verbose_name="Bateau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Détail technique",
                "verbose_name_plural": "Détails techniques",
            },
        ),
    ]
