# Generated by Django 5.1.7 on 2025-03-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_app",
            "0004_remove_boat_amenities_remove_boat_technical_details_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("role", models.CharField(max_length=100, verbose_name="Rôle")),
                (
                    "avatar",
                    models.ImageField(upload_to="testimonials/", verbose_name="Avatar"),
                ),
                ("quote", models.TextField(verbose_name="Citation")),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=5,
                        verbose_name="Note",
                    ),
                ),
            ],
            options={
                "verbose_name": "Témoignage",
                "verbose_name_plural": "Témoignages",
            },
        ),
        migrations.AlterModelOptions(
            name="amenityitem",
            options={
                "verbose_name": "Équipement (facultatif)",
                "verbose_name_plural": "Équipements (facultatif)",
            },
        ),
        migrations.AlterModelOptions(
            name="technicaldetailitem",
            options={
                "verbose_name": "Détail technique (facultatif)",
                "verbose_name_plural": "Détails techniques (facultatif)",
            },
        ),
    ]
