# Generated by Django 5.1.7 on 2025-03-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0005_testimonial_alter_amenityitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boatcategory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="categories/", verbose_name="Image"
            ),
        ),
    ]
