# Generated by Django 5.1.7 on 2025-03-22 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0006_boatcategory_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoatVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Titre"),
                ),
                (
                    "video_url",
                    models.URLField(
                        help_text="YouTube ou Vimeo URL", verbose_name="URL Vidéo"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="boat_video_thumbnails/",
                        verbose_name="Miniature",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Vidéo principale"),
                ),
                (
                    "boat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="api_app.boat",
                        verbose_name="Bateau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vidéo de bateau",
                "verbose_name_plural": "Vidéos de bateaux",
            },
        ),
    ]
