# Generated by Django 5.1.7 on 2025-03-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0007_boatvideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="boatvideo",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Téléchargez directement un fichier vidéo",
                null=True,
                upload_to="boat_videos/",
                verbose_name="Fichier Vidéo",
            ),
        ),
        migrations.AlterField(
            model_name="boatvideo",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube ou Vimeo URL",
                null=True,
                verbose_name="URL Vidéo",
            ),
        ),
    ]
