# Generated by Django 5.1.7 on 2025-03-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0008_boatvideo_video_file_alter_boatvideo_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="boatvideo",
            name="file_size_mb",
            field=models.FloatField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Taille du fichier (MB)",
            ),
        ),
        migrations.AlterField(
            model_name="boatvideo",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Téléchargez directement un fichier vidéo (recommandé < 100 MB)",
                null=True,
                upload_to="boat_videos/",
                verbose_name="Fichier Vidéo",
            ),
        ),
    ]
