# Generated by Django 5.1.7 on 2025-03-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0009_boatvideo_file_size_mb_alter_boatvideo_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="boatvideo",
            name="warning_message",
            field=models.TextField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Message d'avertissement",
            ),
        ),
    ]
