# Generated by Django 5.1.7 on 2025-03-23 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0010_boatvideo_warning_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/", verbose_name="Image"
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de publication",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Publié")),
            ],
            options={
                "verbose_name": "Article de blog",
                "verbose_name_plural": "Articles de blog",
                "ordering": ["-published_date"],
            },
        ),
    ]
