# Generated by Django 5.1.7 on 2025-03-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0011_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="boat",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Mise en avant"),
        ),
    ]
